# Generated by Django 3.2.7 on 2021-11-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_auto_20211104_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email addresss'),
        ),
    ]
