# Generated by Django 3.2.7 on 2021-11-05 03:03

import Leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0003_auto_20211104_2354'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Leads.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
