# Generated by Django 3.2.7 on 2021-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0005_auto_20211105_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
