# Generated by Django 3.2.7 on 2021-11-05 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0007_auto_20211105_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.AddField(
            model_name='lead',
            name='birthday',
            field=models.DateTimeField(default='1995-08-05', help_text='YYYY-MM-DD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
