# Generated by Django 3.2.7 on 2021-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0009_auto_20211108_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Working', 'Working'), ('Customer', 'Customer'), ('Nurture', 'Nurture'), ('Inactive', 'Inactive')], max_length=50, null=True),
        ),
    ]
