# Generated by Django 3.2.7 on 2021-11-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0010_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Working', 'Working'), ('Customer', 'Customer'), ('Nurture', 'Nurture'), ('Inactive', 'Inactive')], default='Open', max_length=50, null=True),
        ),
    ]
